name = "lunch-slack-bot"
main = "worker.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 11 * * 1-5"]  # 平日11時に実行

# 環境変数はwrangler secret putで設定
# wrangler secret put GOOGLE_SHEETS_API_KEY
# wrangler secret put SLACK_BOT_TOKEN
# wrangler secret put SLACK_CHANNEL_ID
# wrangler secret put GOOGLE_SHEET_ID
